version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservice-network

  mysql:
      image: chtaybo22/mysql-custom:latest
      container_name: mysql-db
      ports:
        - "3307:3306"
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      networks:
        - microservice-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservice-network

  client-service:
    image: chtaybo22/ms-client:latest
    container_name: client-service
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - microservice-network
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DB_HOST=mysql-db
      - DB_NAME=client_db  # Base de données pour client-service
      - DB_USER=root
      - DB_PASSWORD=
    #command: ["python", "-m", "API.client_api"]
    command: ["python", "-m", "client_api"]

  produit-service:
    image: chtaybo22/ms-produit:latest
    container_name: produit-service
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - microservice-network
    ports:
      - "5002:5002"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DB_HOST=mysql-db
      - DB_NAME=produit_db  # Base de données pour produit-service
      - DB_USER=root
      - DB_PASSWORD=
    command: ["python", "-m", "produit_api"]

  commande-service:
    image: chtaybo22/ms-commande:latest
    container_name: commande-service
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - microservice-network
    ports:
      - "5003:5003"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DB_HOST=mysql-db
      - DB_NAME=commande_db  # Base de données pour commande-service
      - DB_USER=root
      - DB_PASSWORD=
    command: ["python", "-m", "commande_api"]





networks:
  microservice-network:
    driver: bridge
