global:
  scrape_interval: 15s  # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'ms-produit'
    static_configs:
      - targets: ['ms-produit:8000']  # Le port où Prometheus récupère les métriques

  - job_name: 'ms-client'
    static_configs:
      - targets: ['ms-client:8000']  # Endpoint de métriques du service client

  - job_name: 'ms-commande'
    static_configs:
      - targets: ['ms-commande:8000']  # Endpoint de métriques du service commande
