global:
  scrape_interval: 15s  # Fréquence de collecte des métriques

scrape_configs:

  - job_name: 'ms-produit'
    metrics_path: /metrics
    static_configs:
      - targets: ['produit-service:5002']
  - job_name: 'ms-client'
    metrics_path: /metrics
    static_configs:
      - targets: ['client-service:5001']

  - job_name: 'ms-commande'
    metrics_path: /metrics
    static_configs:
      - targets: ['commande-service:5003']